
- hosts: slave
  become: yes
  gather_facts: false
  tasks:
          - name: To ensure that Java is Running or not
            apt:
                    name: openjdk-8-jdk
                    state: present
                    update_cache: yes

          - name: Adding key to system
            apt_key:
                    url: https://pkg.jenkins.io/debian-stable/jenkins.io.key
                    state: present

          - name: Setting up the Repository
            apt_repository:
                    repo: 'deb https://pkg.jenkins.io/debian-stable binary/'
                    state: present

          - name: Jenkins installation and tomcat installation
            apt:
                    name: "{{item}}"
            
            with_item:
                - jenkins
                - tomcat8
                    state: present
                    update_cache: yes

          - name: To start jenkins services
            service:
                    name: jenkins
                    state: started
                    enabled: yes

